apiVersion: demo.anthos.com/v1
kind: CompositeClusterVpc
metadata:
  name: cluster-vpc-1
spec:
#  compositeDeletePolicy: Foreground
  compositionRef:
    name: cluster-vpc-gke-on-aws
  parameters:
    # managementPolicy: ObserveOnly #toggle to remove management
    awsRegion: "us-west-2"
    gcpRegion: "us-west1"
    name: "gke-on-aws-vpc-1"
    gcpProjectNumber: "933682497375"
    k8sVersion: "1.26.7-gke.500"
    fleetProject: "projects/933682497375"
    gcpProjectId: "zicong-gke-multi-cloud-dev-2"
    adminUsers:
    - "zicong@google.com"