#Demo of importing a GKE cluster into a given composition
apiVersion: demo.anthos.com/v1
kind: CompositeCluster
metadata:
  name: cluster-2 # name to call the cluster in Cloud Resource Accelerator
spec:
#  compositeDeletePolicy: Foreground
  compositionRef:
    name: cluster-gke-on-aws
  parameters:
    # managementPolicy: ObserveOnly #toggle to remove management
    awsRegion: "us-west-2"
    gcpRegion: "us-west1"
    adminUsers:
    - "zicong@google.com"
    name: "gke-on-aws-cluster-1"
    roleArn: "arn:aws:iam::507099386010:role/zicong-1p-dev-1p_0"
    k8sVersion: "1.26.7-gke.500"
    fleetProject: "projects/933682497375"
    gcpProjectId: "zicong-gke-multi-cloud-dev-2"

    # Following info from the vpc1 status
    configKmsKeyArn: arn:aws:kms:us-west-2:507099386010:key/73795a35-0b31-47a2-9c46-2881ab4d449f
    databaseKmsKeyArn: arn:aws:kms:us-west-2:507099386010:key/c7f2ea5b-5829-4f6a-b321-6b7757e780bc
    iamInstanceProfileControlplane: vpc-1-n722t
    iamInstanceProfileNodepool: vpc-1-w8464
    privateSubnets:
    - subnet-0a1fd2877ecda3dea
    - subnet-0365b9c88d76d92b5
    - subnet-01677e66de673166d
    publicSubnets:
    - subnet-0e0bf8e91487baf8a
    - subnet-0a4af9c7c062b2856
    - subnet-0858c46c7041a5ebc
    vpcId: vpc-07f72e5c750bf0990
