#Demo of importing a GKE cluster into a given composition
apiVersion: demo.anthos.com/v1
kind: CompositeCluster
metadata:
  name: cluster-2 # name to call the cluster in Cloud Resource Accelerator
spec:
#  compositeDeletePolicy: Foreground
  compositionRef:
    name: cluster-gke-on-aws
  parameters:
    # managementPolicy: ObserveOnly #toggle to remove management
    awsRegion: "us-west-2"
    gcpRegion: "us-west1"
    adminUsers:
    - "zicong@google.com"
    name: "gke-on-aws-cluster-1"
    roleArn: "arn:aws:iam::507099386010:role/zicong-1p-dev-1p_0"
    iamInstanceProfileControlplane: "zicong-1p-dev-cp-0"
    iamInstanceProfileNodepool: "zicong-1p-dev-np-0"
    k8sVersion: "1.26.7-gke.500"
    fleetProject: "projects/933682497375"
    gcpProjectId: "zicong-gke-multi-cloud-dev-2"
    configKmsKeyArn: arn:aws:kms:us-west-2:507099386010:key/e4dc010a-d94b-493d-9050-cad40bce771e
    databaseKmsKeyArn: arn:aws:kms:us-west-2:507099386010:key/1bc62b93-de29-4ed5-9060-6ccbb40d361f
    publicSubnets:
    - subnet-0f8b71773b25e022d
    - subnet-0d3b19c26f09afd54
    - subnet-0f8b40a8296baaa01
    privateSubnets:
    - subnet-02625633bc431ba6b
    - subnet-00e30191a3f15be4f
    - subnet-0ca69431ad9b88133
    vpcId: vpc-027d750edca3a8683