#Demo of importing a GKE cluster into a given composition
apiVersion: demo.anthos.com/v1
kind: CompositeCluster
metadata:
  name: cluster-2 # name to call the cluster in Cloud Resource Accelerator
spec:
#  compositeDeletePolicy: Foreground
  compositionRef:
    name: cluster-gke-on-aws
  parameters:
    # managementPolicy: ObserveOnly #toggle to remove management
    awsRegion: "us-west-2"
    gcpRegion: "us-west1"
    adminUsers:
    - "zicong@google.com"
    name: "gke-on-aws-cluster-1"
    k8sVersion: "1.26.7-gke.500"
    fleetProject: "projects/933682497375"
    gcpProjectId: "zicong-gke-multi-cloud-dev-2"

    # Following info from the vpc1 status
    apiRoleArn: arn:aws:iam::507099386010:role/vpc-1-2z5fd
    configKmsKeyArn: arn:aws:kms:us-west-2:507099386010:key/51e8fd15-b3ea-4129-92cb-5eb909124b84
    databaseKmsKeyArn: arn:aws:kms:us-west-2:507099386010:key/851818dc-79c3-4f57-ad52-07a1f718211e
    iamInstanceProfileControlplane: vpc-1-9p2gg
    iamInstanceProfileNodepool: vpc-1-7lkst
    privateSubnets:
    - subnet-07e2bed22305b69bd
    - subnet-0fa6085c93ad49ac2
    - subnet-00c7b62439e9950fd
    publicSubnets:
    - subnet-03a19c79050ab78a3
    - subnet-0ebd6995b8ec3435f
    - subnet-08fcdc66e065ae00b
    vpcId: vpc-02c700a0bbfe2429c
